class Settings:
    def __init__(
        self,
        *,
        column_width: int,
        indent: int,
        table_format: str,
        expand_tables: list[str],
        collapse_tables: list[str],
        skip_wrap_for_keys: list[str],
    ) -> None: ...
    @property
    def column_width(self) -> int: ...
    @property
    def indent(self) -> int: ...
    @property
    def table_format(self) -> str: ...
    @property
    def expand_tables(self) -> list[str]: ...
    @property
    def collapse_tables(self) -> list[str]: ...
    @property
    def skip_wrap_for_keys(self) -> list[str]: ...

def format_toml(content: str, settings: Settings) -> str: ...
