from collections.abc import Sequence

class Settings:
    def __init__(
        self,
        *,
        column_width: int,
        indent: int,
        keep_full_version: bool,
        max_supported_python: tuple[int, int],
        min_supported_python: tuple[int, int],
        generate_python_version_classifiers: bool,
        table_format: str,
        sub_table_spacing: str,
        separate_root_table: str,
        expand_tables: Sequence[str],
        collapse_tables: Sequence[str],
        skip_wrap_for_keys: Sequence[str],
    ) -> None: ...
    @property
    def column_width(self) -> int: ...
    @property
    def indent(self) -> int: ...
    @property
    def keep_full_version(self) -> bool: ...
    @property
    def max_supported_python(self) -> tuple[int, int]: ...
    @property
    def min_supported_python(self) -> tuple[int, int]: ...
    @property
    def table_format(self) -> str: ...
    @property
    def sub_table_spacing(self) -> str: ...
    @property
    def separate_root_table(self) -> str: ...
    @property
    def expand_tables(self) -> Sequence[str]: ...
    @property
    def collapse_tables(self) -> Sequence[str]: ...
    @property
    def skip_wrap_for_keys(self) -> Sequence[str]: ...

def format_toml(content: str, settings: Settings) -> str: ...
