version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
    rust: "latest"
  commands:
    - pip install tox-uv
    - tox -c tox-toml-fmt/tox.toml run -e docs -vv --notest
    - tox -c tox-toml-fmt/tox.toml run -e docs --skip-pkg-install --
