name: 🧪 common
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["common/**", ".github/workflows/common.yaml"]
  pull_request:
    paths: ["common/**", ".github/workflows/common.yaml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  clippy:
    name: 📎 clippy
    runs-on: ubuntu-24.04
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: 🦀 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
        with:
          components: clippy
      - name: 📎 Run Clippy
        run: cargo clippy -p common --locked --all-targets -- -D warnings

  fmt:
    name: 🎨 fmt
    runs-on: ubuntu-24.04
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: 🦀 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
        with:
          components: rustfmt
      - name: 🎨 Check formatting
        run: cargo fmt -p common --check

  build:
    name: 🔨 build
    runs-on: ubuntu-24.04
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: 🦀 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
      - name: 🔨 Build
        run: cargo build -p common --locked

  test:
    name: ✅ test
    runs-on: ubuntu-24.04
    environment: test
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: 🦀 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
        with:
          components: llvm-tools-preview
      - name: 📦 Install cargo-llvm-cov
        uses: taiki-e/install-action@7bc99eee1f1b8902a125006cf790a1f4c8461e63 # v2
        with:
          tool: cargo-llvm-cov
      - name: ✅ Run tests with coverage
        run: cargo llvm-cov -p common --no-default-features --locked --codecov --output-path coverage.json --ignore-filename-regex 'create\.rs'
      - name: 📤 Upload coverage
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.json
          flags: rust
