name: 📦 tox-toml-fmt
on:
  workflow_dispatch:
    inputs:
      release:
        description: "🚀 Release (semver bump)?"
        required: true
        default: "no"
        type: choice
        options: ["no", patch, minor, major]
  push:
    branches: ["main"]
    paths:
      - "common/**"
      - "toml-fmt-common/**"
      - "tox-toml-fmt/**"
      - ".github/workflows/tox_toml_fmt_build.yaml"
      - ".github/workflows/_build.yaml"
  pull_request:
    paths:
      - "common/**"
      - "toml-fmt-common/**"
      - "tox-toml-fmt/**"
      - ".github/workflows/tox_toml_fmt_build.yaml"
      - ".github/workflows/_build.yaml"
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ github.event.inputs.release && github.event.inputs.release != 'no' && '-release' || '' }}
  cancel-in-progress: ${{ github.event.inputs.release == 'no' || github.event.inputs.release == null }}

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      package-name: tox-toml-fmt
      pre-commit-mirror: tox-dev/tox-toml-fmt
    secrets: inherit # zizmor: ignore[secrets-inherit]
    permissions:
      contents: write
      id-token: write
      pull-requests: read
