name: 📦 tox-toml-fmt
on:
  workflow_dispatch:
    inputs:
      release:
        description: "🚀 Release (semver bump)?"
        required: true
        default: "no"
        type: choice
        options: ["no", patch, minor, major]
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ github.event.inputs.release && github.event.inputs.release != 'no' && '-release' || '' }}
  cancel-in-progress: ${{ github.event.inputs.release == 'no' || github.event.inputs.release == null }}

permissions:
  contents: read

jobs:
  changes:
    name: 🔍 changes
    runs-on: ubuntu-latest
    outputs:
      run: ${{ github.event_name != 'pull_request' || steps.filter.outputs.run == 'true' }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: 🔍 Check for changes
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            run:
              - 'common/**'
              - 'toml-fmt-common/**'
              - 'tox-toml-fmt/**'
              - '.github/workflows/tox_toml_fmt_build.yaml'

  bump:
    name: 🔖 bump
    needs: changes
    if: needs.changes.outputs.run == 'true'
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    outputs:
      version: ${{ steps.v.outputs.version }}
      changelog: ${{ steps.v.outputs.changelog }}
    steps:
      - name: 🦀 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1
      - name: 📦 Install cargo-edit
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3
        with:
          crate: cargo-edit
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 🔖 Bump version
        run: cargo set-version -p tox-toml-fmt --bump "$RELEASE_TYPE"
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release == 'no' || github.event.inputs.release == null && 'patch' || github.event.inputs.release }}
      - name: 📦 Setup uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          enable-cache: true
          cache-dependency-glob: "tasks/changelog.py"
      - name: 📝 Generate changelog
        id: v
        run: uv run tasks/changelog.py tox-toml-fmt "${{ github.event.number }}" "${{ github.event.pull_request.base.sha }}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 🐍 Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"
      - name: 🎨 Run pre-commit
        uses: tox-dev/action-pre-commit-uv@246b66536e366bb885f52d61983bf32f7c95e8b1 # v1.0.3
        continue-on-error: true
      - name: 📝 Generate README.rst
        run: python tasks/generate_readme.py tox-toml-fmt
      - name: 👀 Show changes
        run: git diff HEAD -u
      - name: 📤 Upload source
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: source
          path: |
            .
            !.git
          compression-level: 9
          retention-days: 1
          if-no-files-found: "error"

  linux:
    name: 🐧 ${{ matrix.platform.target }}
    needs: [bump]
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { runner: ubuntu-24.04, target: x86_64, manylinux: "2_28", interpreter: "3.10 pypy3.11" }
          - { runner: ubuntu-24.04, target: x86_64-unknown-linux-musl, manylinux: musllinux_1_2 }
          - { runner: ubuntu-24.04, target: aarch64, manylinux: "2_28", zig: true }
          - { runner: ubuntu-24.04, target: riscv64gc-unknown-linux-gnu, manylinux: "2_31" }
    steps:
      - name: 📥 Download source
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: source
      - name: 🔨 Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          target: ${{ matrix.platform.target }}
          args: -m tox-toml-fmt/Cargo.toml --locked --release --out dist --interpreter ${{ matrix.platform.interpreter || '3.10' }} --target-dir target ${{ matrix.platform.zig && '--zig' || '' }}
          manylinux: ${{ matrix.platform.manylinux || 'auto' }}
          sccache: true
      - name: 📤 Upload wheels
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: dist

  windows:
    name: 🪟 ${{ matrix.platform.target }}
    needs: [bump]
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { runner: windows-2025, target: x64 }
    steps:
      - name: 📥 Download source
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: source
      - name: 🐍 Setup Python 3.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.10"
          architecture: ${{ matrix.platform.target == 'x86' && 'x86' || 'x64' }}
      - name: 🔨 Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          target: ${{ matrix.platform.target }}
          args: -m tox-toml-fmt/Cargo.toml --locked --release --out dist --interpreter ${{ matrix.platform.interpreter || '3.10' }} --target-dir target
          sccache: true
      - name: 📤 Upload wheels
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: wheels-windows-${{ matrix.platform.target }}
          path: dist

  macos:
    name: 🍎 ${{ matrix.platform.target }}
    needs: [bump]
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { runner: macos-15, target: x86_64 }
          - { runner: macos-15, target: aarch64 }
    steps:
      - name: 📥 Download source
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: source
      - name: 🔨 Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          target: ${{ matrix.platform.target }}
          args: -m tox-toml-fmt/Cargo.toml --locked --release --out dist --interpreter "3.10 pypy3.11" --target-dir target
          sccache: true
      - name: 📤 Upload wheels
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: dist

  sdist:
    name: 📦 sdist
    needs: [bump]
    runs-on: ubuntu-24.04
    steps:
      - name: 📥 Download source
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: source
      - name: 📦 Build sdist
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          command: sdist
          args: -m tox-toml-fmt/Cargo.toml --out dist
      - name: 📤 Upload sdist
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: wheels-sdist
          path: dist

  release:
    name: 🚀 release
    runs-on: ubuntu-24.04
    environment:
      name: release
      url: https://pypi.org/project/tox-toml-fmt/${{ needs.bump.outputs.version }}
    permissions:
      id-token: write
      contents: write
    if: github.event.inputs.release != 'no' && github.event.inputs.release != null && github.ref == 'refs/heads/main'
    needs: [bump, sdist, linux, macos, windows]
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          persist-credentials: false
      - name: 📥 Download source
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: source
          path: .
      - name: 👀 Show changes
        run: git diff HEAD -u
      - name: 💾 Commit release
        run: |
          git config --global user.name 'Bernat Gabor'
          git config --global user.email 'gaborbernat@users.noreply.github.com'
          git commit -am "Release tox-toml-fmt ${NEEDS_BUMP_OUTPUTS_VERSION} [skip ci]"
        env:
          NEEDS_BUMP_OUTPUTS_VERSION: ${{needs.bump.outputs.version}}
      - name: 📥 Download wheels
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: "true"
      - name: 👀 Show wheels
        run: ls -lth dist
      - name: 🚀 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          skip-existing: true
      - name: 📢 Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NEEDS_BUMP_OUTPUTS_VERSION: ${{needs.bump.outputs.version}}
          NEEDS_BUMP_OUTPUTS_CHANGELOG: ${{ needs.bump.outputs.changelog }}
        run: |
          git pull --rebase origin main
          git tag tox-toml-fmt/${NEEDS_BUMP_OUTPUTS_VERSION}
          git push
          git push --tags
          gh release create "tox-toml-fmt/${NEEDS_BUMP_OUTPUTS_VERSION}" \
              --title="tox-toml-fmt/${NEEDS_BUMP_OUTPUTS_VERSION}" --verify-tag \
            --notes "$(cat << 'EOM'
          ${NEEDS_BUMP_OUTPUTS_CHANGELOG}
          EOM
          )"
      - name: 🔄 Trigger pre-commit mirror sync
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: gh workflow run main.yaml --repo tox-dev/tox-toml-fmt

  all-pass:
    name: ✅ tox-toml-fmt-build
    if: always()
    needs: [changes, bump, linux, windows, macos, sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether all jobs passed or were skipped
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "Some jobs failed or were canceled"
            exit 1
          fi
          echo "All jobs passed or were skipped"
